services:
  github-runner:
    build: .
    restart: unless-stopped
    environment:
      URL: ${URL}
      RUNNER_TOKEN: ${RUNNER_TOKEN}
      RUNNER_NAME: ${RUNNER_NAME}
    deploy:
      replicas: ${RUNNER_COUNT:-1}

volumes:
  runner-data:
